// src/app/pricing/config/pricingData.js

export const seekerPlans = [
  {
    id: 'free',
    planId: null,
    name: 'Free',
    price: 0,
    period: 'forever',
    description: 'Explore opportunities at your own pace.',
    badge: null,
    cta: 'Get Started',
    ctaHref: '/signup?role=seeker',
    features: [
      'Browse all job listings',
      'Save up to 10 jobs',
      'Up to 3 job applications',
      'Basic profile page',
      'Email notifications',
    ],
  },
  {
    id: 'pro',
    planId: 'seeker-pro',
    name: 'Pro',
    price: 29,
    period: 'mo',
    description: 'Apply faster, track smarter, land sooner.',
    badge: 'Most Popular',
    cta: 'Upgrade to Pro',
    ctaHref: null,
    features: [
      'Everything in Free',
      'Maximum 50 jobs applications',
      'Unlimited saved jobs',
      'Priority application badge',
      'Application tracking dashboard',
      'Salary insights & analytics',
    ],
  },
  {
    id: 'enterprise',
    planId: 'seeker-enterprise',
    name: 'Enterprise',
    price: 79,
    period: 'mo',
    description: 'Career coaching, headhunting & white-glove support.',
    badge: null,
    cta: 'Upgrade to Enterprise',
    ctaHref: null,
    features: [
      'Everything in Pro',
      'Dedicated career coach',
      'Resume & profile review',
      'Direct recruiter introductions',
      'Interview preparation sessions',
      'Priority customer support',
    ],
  },
];

export const recruiterPlans = [
  {
    id: 'free',
    planId: null,
    name: 'free',
    price: 0,
    period: 'forever',
    description: 'Post your first role and find great candidates.',
    badge: null,
    cta: 'Post a Job Free',
    ctaHref: '/signup?role=recruiter',
    features: [
      '1 active job post',
      'Up to 20 applicants per post',
      'Basic applicant view',
      'Email alerts on new applications',
    ],
  },
  {
    id: 'pro',
    planId: 'recruiter-pro',
    name: 'Pro',
    price: 49,
    period: 'mo',
    description: 'Streamline hiring for growing teams.',
    badge: 'Most Popular',
    cta: 'Start Hiring',
    ctaHref: null,
    features: [
      'Everything in Starter',
      'Up to 10 active job posts',
      'Unlimited applicants',
      'Basic ATS & pipeline view',
      'Team access (up to 3 seats)',
      'Analytics overview',
    ],
  },
  {
    id: 'enterprise',
    planId: 'recruiter-enterprise',
    name: 'Enterprise',
    price: 99,
    period: 'mo',
    description: 'Full-scale hiring infrastructure for large teams.',
    badge: null,
    cta: 'Upgrade to Enterprise',
    ctaHref: null,
    features: [
      'Everything in Pro',
      'Unlimited job postings',
      'Full Applicant Tracking System',
      'Unlimited team seats',
      'Advanced analytics dashboard',
      'Custom branding on listings',
      'Dedicated account manager',
    ],
  },
];
